config/routes.rb
Rails.application.routes.draw do
  root "pages#index"

  get "/features" => "pages#features"
  get "/faq" => "pages#faq"
  get "/about" => "pages#about"
  
  devise_for :users
  
  resources :stadiums, only: [:index]
  resources :tailgates, except: [:show, :edit]
  resources :advices, only: [:new, :show, :edit, :create, :update, :destroy]
  resources :hotels, only: [:new, :create, :update]
  resources :lots, except: [:index, :delete, :show, :edit]
  resources :restaurants, except: [:index, :delete, :show, :edit]
  resources :likes, only: [:create, :destroy]

  get ":name/hotels" => "hotels#index", as: :hotels_by_stadium
  get "/hotels/:name" => "hotels#show", as: :hotel_by_stadium
  get "/hotels/:name/edit" => "hotels#edit", as: :edit_hotel
  
  get ":name/tailgates" => "tailgates#by_stadium", as: :tailgates_by_stadium
  get "/tailgates/:name" => "tailgates#show", as: :tailgate_by_stadium
  get "/tailgates/:name/edit" => "tailgates#edit", as: :edit_tailgate
  
  get ":name/lots" => "lots#index", as: :lots_by_stadium
  get "lots/:name" => "lots#show", as: :lot_by_stadium
  get "/lots/:name/edit" => "lots#edit", as: :edit_lot
  
  get ":name/restaurants" => "restaurants#index", as: :restaurants_by_stadium
  get "restaurants/:name" => "restaurants#show", as: :restaurant_by_stadium
  get "/restaurants/:name/edit" => "restaurants#edit", as: :edit_restaurant

  get "user/:username" => "users#show", as: :user
  
  get ":name" => "stadiums#show", as: :stadium
end

app/models/tailgate.rb
class Tailgate < ApplicationRecord
  validates :name, :address, :stadium_id, presence: true
  validates :name, uniqueness: true

  belongs_to :stadium
  has_many :advices, as: :adviceable, dependent: :delete_all
end

app/controllers/tailgates_controller.rb
class TailgatesController < ApplicationController
  before_action :set_tailgate_id, only: :update
  before_action :set_tailgate_name, only: %i[show edit destroy]
  before_action :set_stadium, only: :by_stadium

  def index
    @tailgates = Tailgate.all
    @stadiums = Stadium.all
  end

  def show; end

  def new
    @tailgate = Tailgate.new
  end

  def edit; end

  def create
    @tailgate = Tailgate.new(tailgate_params)

    respond_to do |format|
      if @tailgate.save
        format.html do
          redirect_to tailgate_by_stadium_url(@tailgate.name), notice: 'Tailgate was successfully created.'
        end
        format.json { render :show, status: :created, location: @tailgate }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @tailgate.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @tailgate.update(tailgate_params)
        format.html do
          redirect_to tailgate_by_stadium_url(@tailgate.name), notice: 'Tailgate was successfully updated.'
        end
        format.json { render :show, status: :ok, location: @tailgate }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @tailgate.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @tailgate.destroy!

    respond_to do |format|
      format.html { redirect_to tailgates_url, notice: 'Tailgate was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def by_stadium
    @tailgates = Tailgate.where("stadium_id = #{@stadium_tailgate.id}")
    render 'by_stadium'
  end

  private

  def set_tailgate_id
    @tailgate = Tailgate.find(params[:id])
  end

  def set_tailgate_name
    @tailgate = Tailgate.find_by(name: params[:name])
  end

  def set_stadium
    @stadium_tailgate = Stadium.find_by(name: params[:name])
  end

  def tailgate_params
    params.require(:tailgate).permit(:address, :name, :stadium_id, :description, :link)
  end
end

app/views/tailgates/_form.html.erb
<%= form_with(model: tailgate) do |form| %>
  <% if tailgate.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(tailgate.errors.count, "error") %> prohibited this tailgate from being saved:</h2>

      <ul>
        <% tailgate.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :address, style: "display: block" %>
    <%= form.text_field :address, class: "form-control" %>
  </div>

  <br>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name, class: "form-control" %>
  </div>

  <br>

  <div>
    <%= form.label :stadium_id, style: "display: block" %>
    <%= form.collection_select :stadium_id, Stadium.all, :id, :team, {}, { class: "form-select" } %>
  </div>

  <br>

  <div>
    <%= form.label :link, style: "display: block" %>
    <%= form.text_field :link, class: "form-control" %>
  </div>

  <br>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_area :description, class: "form-control" %>
  </div>

  <br>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/tailgates/_tailgate.html.erb
<div class="card card-generic border-dark mb-3 h-100" style="max-width: 18rem;">
  <%= link_to tailgate_by_stadium_path(tailgate.name), class: "card-header" do %>
    <%= tailgate.name %>
  <% end %>
  <div class="card-body">
    <h5 class="card-title"><%= tailgate.address %></h5>
    <p class="card-text"><%= tailgate.description %></p>
  </div>
</div>

app/views/tailgates/_wide_tailgate.html.erb
<div class="card text-center">
  <div class="card-header">
    <%= link_to stadium_path(tailgate.stadium.name), class: "card-title" do %>
      <h5><%= tailgate.stadium.team %></h5>
    <% end %>
  </div>
  <div class="card-body">
    <h5 class="card-title"> <%= tailgate.name %> </h5>
    <p class="card-text"> <%= tailgate.description %> </p>
    <a href="<%= tailgate.link %>" target="_blank" class="btn btn-primary">Website Link</a>
  </div>
  <div class="card-footer text-body-secondary">
    <% if current_user %>
      <%= link_to "Edit this Tailgate", edit_tailgate_path(@tailgate.name), class: "btn btn-outline-success m-1" %>
    <% end %>
  </div>
</div>

app/views/tailgates/by_stadium.html.erb
<h1>Tailgates for <%= @stadium_tailgate.name %></h1>

<div class="d-flex p-2 justify-content-around flex-wrap">
  <% @tailgates.each do |tailgate| %>
    <div class="m-3">
      <%= render tailgate %>
    </div>
  <% end %>
</div>

<div class="d-flex justify-content-center">
  <div>
    <%= link_to "New tailgate", new_tailgate_path, class: "btn btn-outline-success m-2"%>
  </div>
  <div>
    <%= link_to "Back to stadium", stadium_path(@stadium_tailgate.name), class: "btn btn-outline-primary m-2"%>
  </div>
</div>

app/views/tailgates/edit.html.erb
<h1>Editing tailgate</h1>

<%= render "form", tailgate: @tailgate %>

<br>

<div>
  <%= link_to tailgate_by_stadium_path(@tailgate.name) do %>
    Show this tailgate
  <% end %> |
  <%= link_to "Back to tailgates", tailgates_path %>
</div>

app/views/tailgates/index.html.erb
<h1>Tailgates</h1>

<br>

<div class="d-flex-reverse p-2">
  <% @stadiums.each do |stadium| %>
    <%= link_to stadium_path(stadium.name), class: "table-link-name" do %>
        <h2><%= stadium.name %></h2>
      <% end %>
    <div>
      <table class="table-tailgate m-2 <%=stadium.nick_name%>-row">
        <tr>
          <th scope="col">Name</th>
          <th scope="col">Address</th>
          <th scope="col">Link</th>
        </tr>
        <% stadium.tailgates.each do |tailgate| %>
          <tr>
            <td> <%= tailgate.name %> </td>
            <td> <%= tailgate.address %> </td>
            <td>
              <%= link_to tailgate_by_stadium_path(tailgate.name), class: "card-header" do %>
                Tailgate page
              <% end %>
            </td>
          </tr>
        <% end %>
      </table>
    </div>
    <br>
  <% end %>
</div>

<% if current_user %>
  <%= link_to "New tailgate", new_tailgate_path, class: "btn btn-outline-success m-2" %>  
<% end %>

app/views/tailgates/new.html.erb
<h1>New tailgate</h1>

<%= render "form", tailgate: @tailgate %>

<br>

<div>
  <%= link_to "Back to tailgates", tailgates_path %>
</div>

app/views/tailgates/show.html.erb
<div class="d-flex justify-content-center">
  <%= render "wide_tailgate", :tailgate => @tailgate %>
</div>

<br>

<div class="d-flex justify-content-center">
  <%= render "/shared/map_card", :map => @tailgate %>
</div>


<h3 class="mt-2">Helpful Tips!</h3>

<hr>

<ul class="list-group list-group-flush">
  <% @tailgate.advices.each do |advice| %>
    <li class="list-group-item">
      <%= render advice %>
    </li>
  <% end %>
</ul>

<div  class="card-body">
  <% if current_user %>
    <h3>Share your tips!</h3>
    <%= render "advices/form", advice: Advice.new(adviceable_id: @tailgate.id, adviceable_type: @tailgate.class, user_id: current_user.id) %>
  <% end %>
  
</div>

<br>

<div class="d-flex">
  <div>
    <%= link_to "All Tailgates", tailgates_path, class: "btn btn-outline-primary m-2" %>
  </div>

  <div>
    <%= link_to "#{@tailgate.stadium.team} Tailgates", tailgates_by_stadium_path(@tailgate.stadium.name), class: "btn btn-outline-success m-2" %>
  </div>
</div>