config/routes.rb
Rails.application.routes.draw do
  root "pages#index"

  get "/features" => "pages#features"
  get "/faq" => "pages#faq"
  get "/about" => "pages#about"
  
  devise_for :users
  
  resources :stadiums, only: [:index]
  resources :tailgates, except: [:show, :edit]
  resources :advices, only: [:new, :show, :edit, :create, :update, :destroy]
  resources :hotels, only: [:new, :create, :update]
  resources :lots, except: [:index, :delete, :show, :edit]
  resources :restaurants, except: [:index, :delete, :show, :edit]
  resources :likes, only: [:create, :destroy]

  get ":name/hotels" => "hotels#index", as: :hotels_by_stadium
  get "/hotels/:name" => "hotels#show", as: :hotel_by_stadium
  get "/hotels/:name/edit" => "hotels#edit", as: :edit_hotel
  
  get ":name/tailgates" => "tailgates#by_stadium", as: :tailgates_by_stadium
  get "/tailgates/:name" => "tailgates#show", as: :tailgate_by_stadium
  get "/tailgates/:name/edit" => "tailgates#edit", as: :edit_tailgate
  
  get ":name/lots" => "lots#index", as: :lots_by_stadium
  get "lots/:name" => "lots#show", as: :lot_by_stadium
  get "/lots/:name/edit" => "lots#edit", as: :edit_lot
  
  get ":name/restaurants" => "restaurants#index", as: :restaurants_by_stadium
  get "restaurants/:name" => "restaurants#show", as: :restaurant_by_stadium
  get "/restaurants/:name/edit" => "restaurants#edit", as: :edit_restaurant

  get "user/:username" => "users#show", as: :user
  
  get ":name" => "stadiums#show", as: :stadium
end

app/views/shared/_adviceable_link.html.erb
<% if advice.adviceable_type == "Stadium" %>
  <%= link_to "link", stadium_path(Stadium.find(advice.adviceable_id).name) %>
  
<% elsif advice.adviceable_type == "Hotel" %>
  <%= link_to "link", hotel_by_stadium_path(Hotel.find(advice.adviceable_id).name) %>

<% elsif advice.adviceable_type == "Tailgate" %>
  <%= link_to "link", tailgate_by_stadium_path(Tailgate.find(advice.adviceable_id).name) %>

<% elsif advice.adviceable_type == "Restaurant" %>
  <%= link_to "link", restaurant_by_stadium_path(Restaurant.find(advice.adviceable_id).name) %>

<% elsif advice.adviceable_type == "Lot" %>
  <%= link_to "link", lot_by_stadium_path(Lot.find(advice.adviceable_id).name) %>

<% else %>
  <p>oops</p>
<% end %>

app/views/shared/_cdn_assets.html.erb
<!-- Connect Bootstrap CSS -->
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css">

<!-- Connect Bootstrap JavaScript and its dependencies -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"></script>

<!-- Connect Font Awesome -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.6.0/js/all.min.js"></script>

app/views/shared/_flash.html.erb
<div class="alert alert-<%= css_class %> alert-dismissible fade show" role="alert">
  <%= message %>
  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>

app/views/shared/_footer.html.erb
<footer class="py-3 my-4">
  <ul class="nav justify-content-center border-bottom pb-3 mb-3">
    <li class="nav-item">
      <%= link_to "Home", root_path, class: "nav-link px-2 text-body-secondary" %>
    </li>
    <li class="nav-item">
      <%= link_to "Features", features_path, class: "nav-link px-2 text-body-secondary" %>
    </li>
    <li class="nav-item">
      <%= link_to "FAQs", faq_path, class: "nav-link px-2 text-body-secondary" %>
    </li>
    <li class="nav-item">
      <%= link_to "About", about_path, class: "nav-link px-2 text-body-secondary" %>
    </li>
  </ul>
  <p class="text-center text-body-secondary">Tailgators</p>
</footer>

app/views/shared/_map_card.html.erb
<div class="card">
  <div class="card-body">
    <h5 class="card-title">Map Address</h5>
    <p class="card-text"><small class="text-body-secondary"><%=map.address%></small></p>
  </div>
  <a href="https://www.google.com/maps/place/<%=url_encode(map.address)%>" target="_blank">
      <img src="https://maps.googleapis.com/maps/api/staticmap?center=<%=map.address%>&zoom=15&size=1200x150&markers=color:red%7Clabel:Hotel%7C<%=map.address%>&key=<%= Rails.application.credentials.google_maps_key %>" class="card-img-bottom" alt=<%= map.name %>>
    </a>
  
</div>

app/views/shared/_navbar.html.erb
<nav class="navbar bg-dark navbar-expand-lg mb-4" data-bs-theme="dark">
  <div class="container-fluid">
    <%= link_to "Tailgators", root_path, class: "navbar-brand" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <%= link_to "Stadiums", stadiums_path, class: "nav-link active" %>
        </li>
        <li class="nav-item">
          <%= link_to "Tailgates", tailgates_path, class: "nav-link active" %>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link active dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            NFC North
          </a>
          <ul class="dropdown-menu">
            <li><%= link_to "Chicago Bears", stadium_path("Soldier Field"), class: "dropdown-item" %></li>
            <li><%= link_to "Green Bay Packers", stadium_path("Lambeau Field"), class: "dropdown-item" %></li>
            <li><%= link_to "Detroit Lions", stadium_path("Ford Field"), class: "dropdown-item" %></li>
            <li><%= link_to "Minnesota Vikings", stadium_path("US Bank Stadium"), class: "dropdown-item" %></li>
          </ul>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link active dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            AFC West
          </a>
          <ul class="dropdown-menu">
            <li><%= link_to "Kansas City Chiefs", stadium_path("Arrowhead Stadium"), class: "dropdown-item" %></li>
            <li><%= link_to "Las Vegas Raiders", stadium_path("Allegiant Stadium"), class: "dropdown-item" %></li>
            <li><%= link_to "Denver Broncos", stadium_path("Mile High Stadium"), class: "dropdown-item" %></li>
            <li><%= link_to "Los Angeles Chargers", stadium_path("SoFi Stadium (Chargers)"), class: "dropdown-item" %></li>
          </ul>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link active dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            NFC West
          </a>
          <ul class="dropdown-menu">
            <li><%= link_to "Seattle Seahawks", stadium_path("Lumen Field"), class: "dropdown-item" %></li>
            <li><%= link_to "Los Angeles Rams", stadium_path("SoFi Stadium (Rams)"), class: "dropdown-item" %></li>
            <li><%= link_to "San Francisco 49ers", stadium_path("Levi's Stadium"), class: "dropdown-item" %></li>
            <li><%= link_to "Arizona Cardinals", stadium_path("State Farm Stadium"), class: "dropdown-item" %></li>
          </ul>
        </ul>
        <% if user_signed_in? %>
          <li class="nav-item">
            <%= link_to "Settings", edit_user_registration_path, class: "nav-link" %>
          </li>
          <li>
            <%= link_to "Sign out", destroy_user_session_path, data: { turbo_method: :delete }, class: "nav-link" %>
          </li>
          <li>
            <%= link_to "Profile Page", user_path(current_user.username), class: "nav-link" %>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Sign in", new_user_session_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Sign up", new_user_registration_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>