config/routes.rb
Rails.application.routes.draw do
  root "pages#index"

  get "/features" => "pages#features"
  get "/faq" => "pages#faq"
  get "/about" => "pages#about"
  
  devise_for :users
  
  resources :stadiums, only: [:index]
  resources :tailgates, except: [:show, :edit]
  resources :advices, only: [:new, :show, :edit, :create, :update, :destroy]
  resources :hotels, only: [:new, :create, :update]
  resources :lots, except: [:index, :delete, :show, :edit]
  resources :restaurants, except: [:index, :delete, :show, :edit]
  resources :likes, only: [:create, :destroy]

  get ":name/hotels" => "hotels#index", as: :hotels_by_stadium
  get "/hotels/:name" => "hotels#show", as: :hotel_by_stadium
  get "/hotels/:name/edit" => "hotels#edit", as: :edit_hotel
  
  get ":name/tailgates" => "tailgates#by_stadium", as: :tailgates_by_stadium
  get "/tailgates/:name" => "tailgates#show", as: :tailgate_by_stadium
  get "/tailgates/:name/edit" => "tailgates#edit", as: :edit_tailgate
  
  get ":name/lots" => "lots#index", as: :lots_by_stadium
  get "lots/:name" => "lots#show", as: :lot_by_stadium
  get "/lots/:name/edit" => "lots#edit", as: :edit_lot
  
  get ":name/restaurants" => "restaurants#index", as: :restaurants_by_stadium
  get "restaurants/:name" => "restaurants#show", as: :restaurant_by_stadium
  get "/restaurants/:name/edit" => "restaurants#edit", as: :edit_restaurant

  get "user/:username" => "users#show", as: :user
  
  get ":name" => "stadiums#show", as: :stadium
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  validates :name, :stadium_id, presence: true

  belongs_to :stadium
  has_many :advices, as: :adviceable, dependent: :delete_all
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  before_action :set_restaurant_id, only: %i[update destroy]
  before_action :set_restaurant_name, only: %i[show edit]
  before_action :set_stadium, only: :index

  def index
    @restaurants = Restaurant.where("stadium_id = #{@stadium_lot.id}")
  end

  def show; end

  def new
    @restaurant = Restaurant.new
  end

  def edit; end

  def create
    @restaurant = Restaurant.new(restaurant_params)

    respond_to do |format|
      if @restaurant.save
        format.html do
          redirect_to restaurant_by_stadium_url(@restaurant.name), notice: 'Restaurant was successfully created.'
        end
        format.json { render :show, status: :created, location: @restaurant }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @restaurant.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @restaurant.update(restaurant_params)
        format.html do
          redirect_to restaurant_by_stadium_url(@restaurant.name), notice: 'Restaurant was successfully updated.'
        end
        format.json { render :show, status: :ok, location: @restaurant }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @restaurant.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @restaurant.destroy!

    respond_to do |format|
      format.html { redirect_to restaurants_url, notice: 'Restaurant was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  def set_restaurant_id
    @restaurant = Restaurant.find(params[:id])
  end

  def set_restaurant_name
    @restaurant = Restaurant.find_by(name: params[:name])
  end

  def restaurant_params
    params.require(:restaurant).permit(:name, :link, :description, :address, :stadium_id)
  end

  def set_stadium
    @stadium_lot = Stadium.find_by(name: params[:name])
  end
end

app/views/restaurants/_form.html.erb
<%= form_with(model: restaurant) do |form| %>
  <% if restaurant.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(restaurant.errors.count, "error") %> prohibited this restaurant from being saved:</h2>

      <ul>
        <% restaurant.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name, class: "form-control" %>
  </div>

  <div>
    <%= form.label :link, style: "display: block" %>
    <%= form.text_field :link, class: "form-control" %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_area :description, class: "form-control" %>
  </div>

  <div>
    <%= form.label :address, style: "display: block" %>
    <%= form.text_field :address, class: "form-control" %>
  </div>

  <div>
    <%= form.label :stadium_id, style: "display: block" %>
    <%= form.collection_select :stadium_id, Stadium.all, :id, :team, {}, { class: "form-select" } %>
  </div>

  <br>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/restaurants/_restaurant.html.erb
<div class="card card-generic border-dark mb-3 h-100" style="max-width: 18rem;">
  <%= link_to restaurant_by_stadium_path(restaurant.name), class: "card-header" do %>
    <%= restaurant.name %>
  <% end %>
  <div class="card-body">
    <h5 class="card-title"><%= restaurant.address %></h5>
    <p class="card-text"><%= restaurant.description %></p>
  </div>
</div>

app/views/restaurants/_wide_restaurant.html.erb
<div class="card text-center">
  <div class="card-header">
    <%= link_to stadium_path(restaurant.stadium.name), class: "card-title" do %>
      <h5><%= restaurant.stadium.team %></h5>
    <% end %>
  </div>
  <div class="card-body">
    <h5 class="card-title"><%= restaurant.name %></h5>
    <p class="card-text"><%= restaurant.description %></p>
    <a href="<%= restaurant.link %>" target="_blank" class="btn btn-primary">Restaurant Link</a>
  </div>
  <div class="card-footer text-body-secondary">
    <% if current_user %>
      <%= link_to "Edit this Restaurant", edit_restaurant_path(@restaurant.name), class: "btn btn-outline-success m-1" %>
    <% end %>
  </div>
</div>

app/views/restaurants/edit.html.erb
<h1>Editing restaurant</h1>

<%= render "form", restaurant: @restaurant %>

<br>

<div>
  <%= link_to "Show this restaurant", @restaurant %> |
  <%= link_to "Back to restaurants", restaurants_path %>
</div>

app/views/restaurants/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Restaurants</h1>

<div class="d-flex p-2 justify-content-around flex-wrap">
  <% @restaurants.each do |restaurant| %>
    <div class="m-3">
      <%= render restaurant %>
    </div>
  <% end %>
</div>

<div class="d-flex justify-content-center">
  <div>
    <%= link_to "New restaurant", new_restaurant_path, class: "btn btn-outline-success m-2" %>
  </div>
  <div>
    <%= link_to "Back to stadium", stadium_path(@stadium_lot.name), class: "btn btn-outline-primary m-2"%>
  </div>
</div>

app/views/restaurants/new.html.erb
<h1>New restaurant</h1>

<%= render "form", restaurant: @restaurant %>

<br>

<div>
  <%= link_to "Back to home", root_path %>
</div>

app/views/restaurants/show.html.erb
<div class="d-flex justify-content-center">
  <%= render "wide_restaurant", :restaurant => @restaurant %>
</div>

<br>

<div class="d-flex justify-content-center">
  <%= render "/shared/map_card", :map => @restaurant %>
</div>

<h3 class="mt-2">Helpful Tips!</h3>

<hr>

<ul class="list-group list-group-flush">
  <% @restaurant.advices.each do |advice| %>
    <li class="list-group-item">
      <%= render advice %>
    </li>
  <% end %>
</ul>

<div  class="card-body">
  <% if current_user %>
    <h3>Share your tips!</h3>
    <%= render "advices/form", advice: Advice.new(adviceable_id: @restaurant.id, adviceable_type: @restaurant.class, user_id: current_user.id) %>
  <% end %>
  
</div>

<br>

<div>
  <%= link_to "Back to #{@restaurant.stadium.team} restaurants", restaurants_by_stadium_path(@restaurant.stadium.name), class: "btn btn-outline-primary m-2" %>
</div>