config/routes.rb
Rails.application.routes.draw do
  root "pages#index"

  get "/features" => "pages#features"
  get "/faq" => "pages#faq"
  get "/about" => "pages#about"
  
  devise_for :users
  
  resources :stadiums, only: [:index]
  resources :tailgates, except: [:show, :edit]
  resources :advices, only: [:new, :show, :edit, :create, :update, :destroy]
  resources :hotels, only: [:new, :create, :update]
  resources :lots, except: [:index, :delete, :show, :edit]
  resources :restaurants, except: [:index, :delete, :show, :edit]
  resources :likes, only: [:create, :destroy]

  get ":name/hotels" => "hotels#index", as: :hotels_by_stadium
  get "/hotels/:name" => "hotels#show", as: :hotel_by_stadium
  get "/hotels/:name/edit" => "hotels#edit", as: :edit_hotel
  
  get ":name/tailgates" => "tailgates#by_stadium", as: :tailgates_by_stadium
  get "/tailgates/:name" => "tailgates#show", as: :tailgate_by_stadium
  get "/tailgates/:name/edit" => "tailgates#edit", as: :edit_tailgate
  
  get ":name/lots" => "lots#index", as: :lots_by_stadium
  get "lots/:name" => "lots#show", as: :lot_by_stadium
  get "/lots/:name/edit" => "lots#edit", as: :edit_lot
  
  get ":name/restaurants" => "restaurants#index", as: :restaurants_by_stadium
  get "restaurants/:name" => "restaurants#show", as: :restaurant_by_stadium
  get "/restaurants/:name/edit" => "restaurants#edit", as: :edit_restaurant

  get "user/:username" => "users#show", as: :user
  
  get ":name" => "stadiums#show", as: :stadium
end

app/models/lot.rb
class Lot < ApplicationRecord
  validates :name, :stadium_id, presence: true

  belongs_to :stadium
  has_many :advices, as: :adviceable, dependent: :delete_all
end

app/controllers/lots_controller.rb
class LotsController < ApplicationController
  before_action :set_lot_id, only: %i[update destroy]
  before_action :set_lot_name, only: %i[show edit]
  before_action :set_stadium, only: :index

  def index
    @lots = Lot.where("stadium_id = #{@stadium_lot.id}")
  end

  def show; end

  def new
    @lot = Lot.new
  end

  def edit; end

  def create
    @lot = Lot.new(lot_params)

    respond_to do |format|
      if @lot.save
        format.html { redirect_to lot_by_stadium_url(@lot.name), notice: 'Lot was successfully created.' }
        format.json { render :show, status: :created, location: @lot }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @lot.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @lot.update(lot_params)
        format.html { redirect_to lot_by_stadium_url(@lot.name), notice: 'Lot was successfully updated.' }
        format.json { render :show, status: :ok, location: @lot }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @lot.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @lot.destroy!

    respond_to do |format|
      format.html { redirect_to lots_url, notice: 'Lot was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  def set_lot_id
    @lot = Lot.find(params[:id])
  end

  def set_lot_name
    @lot = Lot.find_by(name: params[:name])
  end

  def set_stadium
    @stadium_lot = Stadium.find_by(name: params[:name])
  end

  def lot_params
    params.require(:lot).permit(:address, :description, :name, :link, :stadium_id)
  end
end

app/views/lots/_form.html.erb
<%= form_with(model: lot) do |form| %>
  <% if lot.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(lot.errors.count, "error") %> prohibited this lot from being saved:</h2>

      <ul>
        <% lot.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :address, style: "display: block" %>
    <%= form.text_field :address, class: "form-control" %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_field :description, class: "form-control" %>
  </div>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name, class: "form-control" %>
  </div>

  <div>
    <%= form.label :link, style: "display: block" %>
    <%= form.text_field :link, class: "form-control" %>
  </div>

  <div>
    <%= form.label :stadium_id, style: "display: block" %>
    <%= form.collection_select :stadium_id, Stadium.all, :id, :team, {}, { class: "form-select" } %>
  </div>

  <br>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/lots/_lot.html.erb
<div class="card-lot m-4">
  <div class="card-lot-details">
    <p class="text-lot-title"><%= lot.name %></p>
    <p class="text-lot-body"><%= lot.description %></p>
  </div>
  <%= link_to lot_by_stadium_path(lot.name), class: "card-lot-button" do %>
    More info
  <% end %>
</div>

app/views/lots/_wide_lot.html.erb
<div class="card text-center">
  <div class="card-header">
    <%= link_to stadium_path(lot.stadium.name), class: "card-title" do %>
      <h5><%= lot.stadium.team %></h5>
    <% end %>
  </div>
  <div class="card-body">
    <h5 class="card-title"><%= lot.name %></h5>
    <p class="card-text"><%= lot.description %></p>
    <a href="<%= lot.link %>" target="_blank" class="btn btn-primary">Parking Link</a>
  </div>
  <div class="card-footer text-body-secondary">
    <% if current_user %>
      <%= link_to "Edit this Parking Lot", edit_lot_path(@lot.name), class: "btn btn-outline-success m-1" %>
    <% end %>
  </div>
</div>

app/views/lots/edit.html.erb
<h1>Editing lot</h1>

<%= render "form", lot: @lot %>

<br>

<div>
  <%= link_to "Show this lot", @lot %> |
  <%= link_to "Back to lots", lots_path %>
</div>

app/views/lots/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Lots</h1>

<div class="d-flex p-2 justify-content-around flex-wrap">
  <% @lots.each do |lot| %>
    <div class="m-3">
      <%= render lot %>
    </div>
  <% end %>
</div>

<div class="d-flex justify-content-center">
  <div>
    <%= link_to "New lot", new_lot_path, class: "btn btn-outline-success m-2" %>
  </div>
  <div>
    <%= link_to "Back to stadium", stadium_path(@stadium_lot.name), class: "btn btn-outline-primary m-2"%>
  </div>
</div>

app/views/lots/new.html.erb
<h1>New lot</h1>

<%= render "form", lot: @lot %>

<br>

<div>
  <%= link_to "Back to home", root_path %>
</div>

app/views/lots/show.html.erb
<div class="d-flex justify-content-center">
  <%= render "wide_lot", :lot => @lot %>
</div>

<h3 class="mt-2">Helpful Tips!</h3>

<hr>

<ul class="list-group list-group-flush">
  <% @lot.advices.each do |advice| %>
    <li class="list-group-item">
      <%= render advice %>
    </li>
  <% end %>
</ul>

<div  class="card-body">
  <% if current_user %>
    <h3>Share your tips!</h3>
    <%= render "advices/form", advice: Advice.new(adviceable_id: @lot.id, adviceable_type: @lot.class, user_id: current_user.id) %>
  <% end %>
  
</div>

<br>

<div>
  <%= link_to "Back to #{@lot.stadium.team} lots", lots_by_stadium_path(@lot.stadium.name), class: "btn btn-outline-primary m-2" %>
</div>